//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maptool.DrugsBaseService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DrugsBaseService.DrugsBaseSoap")]
    public interface DrugsBaseSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppendDrugsBaseApply", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AppendDrugsBaseApply(Maptool.DrugsBaseService.DrugsBaseApply model, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppendDrugsBaseBothApplyAudit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Maptool.DrugsBaseService.DrugBaseResult AppendDrugsBaseBothApplyAudit(Maptool.DrugsBaseService.DrugsBaseApply model, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppendDrugsBaseApplyZyc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AppendDrugsBaseApplyZyc(Maptool.DrugsBaseService.DrugsBaseApplyZyc model, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppendDrugsBaseApplyZycAudit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Maptool.DrugsBaseService.DrugBaseResult AppendDrugsBaseApplyZycAudit(Maptool.DrugsBaseService.DrugsBaseApplyZyc model, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyDrugsBaseApply", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ModifyDrugsBaseApply(Maptool.DrugsBaseService.DrugsBaseApply model, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyDrugsBaseApplyZyc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ModifyDrugsBaseApplyZyc(Maptool.DrugsBaseService.DrugsBaseApplyZyc model, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDrugsBaseApply", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteDrugsBaseApply(string id, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDrugsBaseApplyZyc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteDrugsBaseApplyZyc(string id, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrugsBaseApplyList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Maptool.DrugsBaseService.DrugsBaseApply[] GetDrugsBaseApplyList(out int recordCount, out int pageCount, int PageSize, int PageIndex, string source, string[] fields, string[] values, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrugsBaseApplyZycList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Maptool.DrugsBaseService.DrugsBaseApplyZyc[] GetDrugsBaseApplyZycList(out int recordCount, out int pageCount, int PageSize, int PageIndex, string source, string[] fields, string[] values, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDrugsImageApplyList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddDrugsImageApplyList(Maptool.DrugsBaseService.DrugsImageApply[] list, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetDrugsImageApply", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SetDrugsImageApply(int goods_id, int type, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDrugsImageApply", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteDrugsImageApply(string[] list, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDrugsImageApplyId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteDrugsImageApplyId(int id, string key, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrugsbaseAllList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDrugsbaseAllList(int PageSize, int PageIndex, string[] where, string[] values, bool drugs, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrugsImageApplyList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDrugsImageApplyList(int PageSize, int PageIndex, string source, string[] where, string[] values, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Maptool.DrugsBaseService.DrugsImageApply[] GetListArray(string strWhere, int type, string source, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDrugsImageApply", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddDrugsImageApply(Maptool.DrugsBaseService.DrugsImageApply model, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDrugsImageApply", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateDrugsImageApply(Maptool.DrugsBaseService.DrugsImageApply model, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrugsBaseEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetDrugsBaseEnum(Maptool.DrugsBaseService.DrugsBaseEnum de);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrugsBase_Pharm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDrugsBase_Pharm(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrugsBase_Pharm2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDrugsBase_Pharm2(string ids, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOtcClass", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOtcClass(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOtcClass2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOtcClass2(string ids, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDrugsBase_Enterprise", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AddDrugsBase_Enterprise(string Name, decimal lng, decimal lat, int Province, int City, int Borough, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectCompanyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Maptool.DrugsBaseService.EnterpriseLocation[] SelectCompanyName(string q);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEnterpriseList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Maptool.DrugsBaseService.EnterpriseLocation[] GetEnterpriseList();
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DrugsBaseApplyZyc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DrugsBaseApply : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string drugsBase_DrugNameField;
        
        private string drugsBase_ProNameField;
        
        private string drugsBase_SpecificationField;
        
        private string drugsBase_FormulationField;
        
        private string drugsBase_ManufacturerField;
        
        private string drugsBase_ApprovalNumberField;
        
        private string cunchtjField;
        
        private int youXqField;
        
        private int goods_ConveRatioField;
        
        private string goods_ConveRatio_UnitField;
        
        private string goods_ConveRatio_Unit_NameField;
        
        private string goods_UnitField;
        
        private int goods_PcsField;
        
        private int goods_Pcs_SmallField;
        
        private string goods_Package_UnitField;
        
        private string[] imageListField;
        
        private string[] imageListSmallField;
        
        private string drugsbase_Direct_ContextField;
        
        private string sourceField;
        
        private string sourceNameField;
        
        private string statusField;
        
        private System.DateTime createdField;
        
        private System.Nullable<System.DateTime> updatedField;
        
        private string infoField;
        
        private string editerField;
        
        private int drugsBase_IDField;
        
        private int goods_IDField;
        
        private string drugsClassField;
        
        private int[] pharmIDField;
        
        private int[] otcTagClassField;
        
        private int isZYField;
        
        private string describeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DrugsBase_DrugName {
            get {
                return this.drugsBase_DrugNameField;
            }
            set {
                this.drugsBase_DrugNameField = value;
                this.RaisePropertyChanged("DrugsBase_DrugName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DrugsBase_ProName {
            get {
                return this.drugsBase_ProNameField;
            }
            set {
                this.drugsBase_ProNameField = value;
                this.RaisePropertyChanged("DrugsBase_ProName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DrugsBase_Specification {
            get {
                return this.drugsBase_SpecificationField;
            }
            set {
                this.drugsBase_SpecificationField = value;
                this.RaisePropertyChanged("DrugsBase_Specification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DrugsBase_Formulation {
            get {
                return this.drugsBase_FormulationField;
            }
            set {
                this.drugsBase_FormulationField = value;
                this.RaisePropertyChanged("DrugsBase_Formulation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DrugsBase_Manufacturer {
            get {
                return this.drugsBase_ManufacturerField;
            }
            set {
                this.drugsBase_ManufacturerField = value;
                this.RaisePropertyChanged("DrugsBase_Manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DrugsBase_ApprovalNumber {
            get {
                return this.drugsBase_ApprovalNumberField;
            }
            set {
                this.drugsBase_ApprovalNumberField = value;
                this.RaisePropertyChanged("DrugsBase_ApprovalNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string cunchtj {
            get {
                return this.cunchtjField;
            }
            set {
                this.cunchtjField = value;
                this.RaisePropertyChanged("cunchtj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int YouXq {
            get {
                return this.youXqField;
            }
            set {
                this.youXqField = value;
                this.RaisePropertyChanged("YouXq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Goods_ConveRatio {
            get {
                return this.goods_ConveRatioField;
            }
            set {
                this.goods_ConveRatioField = value;
                this.RaisePropertyChanged("Goods_ConveRatio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Goods_ConveRatio_Unit {
            get {
                return this.goods_ConveRatio_UnitField;
            }
            set {
                this.goods_ConveRatio_UnitField = value;
                this.RaisePropertyChanged("Goods_ConveRatio_Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Goods_ConveRatio_Unit_Name {
            get {
                return this.goods_ConveRatio_Unit_NameField;
            }
            set {
                this.goods_ConveRatio_Unit_NameField = value;
                this.RaisePropertyChanged("Goods_ConveRatio_Unit_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Goods_Unit {
            get {
                return this.goods_UnitField;
            }
            set {
                this.goods_UnitField = value;
                this.RaisePropertyChanged("Goods_Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Goods_Pcs {
            get {
                return this.goods_PcsField;
            }
            set {
                this.goods_PcsField = value;
                this.RaisePropertyChanged("Goods_Pcs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int Goods_Pcs_Small {
            get {
                return this.goods_Pcs_SmallField;
            }
            set {
                this.goods_Pcs_SmallField = value;
                this.RaisePropertyChanged("Goods_Pcs_Small");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Goods_Package_Unit {
            get {
                return this.goods_Package_UnitField;
            }
            set {
                this.goods_Package_UnitField = value;
                this.RaisePropertyChanged("Goods_Package_Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public string[] ImageList {
            get {
                return this.imageListField;
            }
            set {
                this.imageListField = value;
                this.RaisePropertyChanged("ImageList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        public string[] ImageListSmall {
            get {
                return this.imageListSmallField;
            }
            set {
                this.imageListSmallField = value;
                this.RaisePropertyChanged("ImageListSmall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Drugsbase_Direct_Context {
            get {
                return this.drugsbase_Direct_ContextField;
            }
            set {
                this.drugsbase_Direct_ContextField = value;
                this.RaisePropertyChanged("Drugsbase_Direct_Context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string sourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
                this.RaisePropertyChanged("sourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<System.DateTime> updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Editer {
            get {
                return this.editerField;
            }
            set {
                this.editerField = value;
                this.RaisePropertyChanged("Editer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int DrugsBase_ID {
            get {
                return this.drugsBase_IDField;
            }
            set {
                this.drugsBase_IDField = value;
                this.RaisePropertyChanged("DrugsBase_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int Goods_ID {
            get {
                return this.goods_IDField;
            }
            set {
                this.goods_IDField = value;
                this.RaisePropertyChanged("Goods_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string DrugsClass {
            get {
                return this.drugsClassField;
            }
            set {
                this.drugsClassField = value;
                this.RaisePropertyChanged("DrugsClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=29)]
        public int[] PharmID {
            get {
                return this.pharmIDField;
            }
            set {
                this.pharmIDField = value;
                this.RaisePropertyChanged("PharmID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=30)]
        public int[] OtcTagClass {
            get {
                return this.otcTagClassField;
            }
            set {
                this.otcTagClassField = value;
                this.RaisePropertyChanged("OtcTagClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public int IsZY {
            get {
                return this.isZYField;
            }
            set {
                this.isZYField = value;
                this.RaisePropertyChanged("IsZY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Describe {
            get {
                return this.describeField;
            }
            set {
                this.describeField = value;
                this.RaisePropertyChanged("Describe");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EnterpriseLocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private decimal lonField;
        
        private decimal latField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
                this.RaisePropertyChanged("Lon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
                this.RaisePropertyChanged("Lat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DrugsImageApply : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int goods_IDField;
        
        private int goods_Package_IDField;
        
        private string imageField;
        
        private string sourceField;
        
        private string sourceNameField;
        
        private int categoryField;
        
        private string statusField;
        
        private string infoField;
        
        private System.DateTime createdField;
        
        private System.DateTime updatedField;
        
        private string editerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Goods_ID {
            get {
                return this.goods_IDField;
            }
            set {
                this.goods_IDField = value;
                this.RaisePropertyChanged("Goods_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Goods_Package_ID {
            get {
                return this.goods_Package_IDField;
            }
            set {
                this.goods_Package_IDField = value;
                this.RaisePropertyChanged("Goods_Package_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("Image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
                this.RaisePropertyChanged("sourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string editer {
            get {
                return this.editerField;
            }
            set {
                this.editerField = value;
                this.RaisePropertyChanged("editer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DrugBaseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int goods_Package_IDField;
        
        private int goods_IDField;
        
        private int drugsBase_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Goods_Package_ID {
            get {
                return this.goods_Package_IDField;
            }
            set {
                this.goods_Package_IDField = value;
                this.RaisePropertyChanged("Goods_Package_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Goods_ID {
            get {
                return this.goods_IDField;
            }
            set {
                this.goods_IDField = value;
                this.RaisePropertyChanged("Goods_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DrugsBase_ID {
            get {
                return this.drugsBase_IDField;
            }
            set {
                this.drugsBase_IDField = value;
                this.RaisePropertyChanged("DrugsBase_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DrugsBaseApplyZyc : DrugsBaseApply {
        
        private string productionClassField;
        
        private string productionBrandField;
        
        private string productionLevelField;
        
        private string productionMethodField;
        
        private string productionAddressField;
        
        private string drugsBase_Formulation_1Field;
        
        private string drugsBase_Manufacturer_FoundryField;
        
        private decimal bagCapacityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductionClass {
            get {
                return this.productionClassField;
            }
            set {
                this.productionClassField = value;
                this.RaisePropertyChanged("ProductionClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductionBrand {
            get {
                return this.productionBrandField;
            }
            set {
                this.productionBrandField = value;
                this.RaisePropertyChanged("ProductionBrand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProductionLevel {
            get {
                return this.productionLevelField;
            }
            set {
                this.productionLevelField = value;
                this.RaisePropertyChanged("ProductionLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ProductionMethod {
            get {
                return this.productionMethodField;
            }
            set {
                this.productionMethodField = value;
                this.RaisePropertyChanged("ProductionMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ProductionAddress {
            get {
                return this.productionAddressField;
            }
            set {
                this.productionAddressField = value;
                this.RaisePropertyChanged("ProductionAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DrugsBase_Formulation_1 {
            get {
                return this.drugsBase_Formulation_1Field;
            }
            set {
                this.drugsBase_Formulation_1Field = value;
                this.RaisePropertyChanged("DrugsBase_Formulation_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DrugsBase_Manufacturer_Foundry {
            get {
                return this.drugsBase_Manufacturer_FoundryField;
            }
            set {
                this.drugsBase_Manufacturer_FoundryField = value;
                this.RaisePropertyChanged("DrugsBase_Manufacturer_Foundry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal BagCapacity {
            get {
                return this.bagCapacityField;
            }
            set {
                this.bagCapacityField = value;
                this.RaisePropertyChanged("BagCapacity");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DrugsBaseEnum {
        
        /// <remarks/>
        存储条件,
        
        /// <remarks/>
        中药类别,
        
        /// <remarks/>
        中药等级,
        
        /// <remarks/>
        中药制法,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DrugsBaseSoapChannel : Maptool.DrugsBaseService.DrugsBaseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DrugsBaseSoapClient : System.ServiceModel.ClientBase<Maptool.DrugsBaseService.DrugsBaseSoap>, Maptool.DrugsBaseService.DrugsBaseSoap {
        
        public DrugsBaseSoapClient() {
        }
        
        public DrugsBaseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DrugsBaseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DrugsBaseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DrugsBaseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AppendDrugsBaseApply(Maptool.DrugsBaseService.DrugsBaseApply model, string key) {
            return base.Channel.AppendDrugsBaseApply(model, key);
        }
        
        public Maptool.DrugsBaseService.DrugBaseResult AppendDrugsBaseBothApplyAudit(Maptool.DrugsBaseService.DrugsBaseApply model, string key) {
            return base.Channel.AppendDrugsBaseBothApplyAudit(model, key);
        }
        
        public int AppendDrugsBaseApplyZyc(Maptool.DrugsBaseService.DrugsBaseApplyZyc model, string key) {
            return base.Channel.AppendDrugsBaseApplyZyc(model, key);
        }
        
        public Maptool.DrugsBaseService.DrugBaseResult AppendDrugsBaseApplyZycAudit(Maptool.DrugsBaseService.DrugsBaseApplyZyc model, string key) {
            return base.Channel.AppendDrugsBaseApplyZycAudit(model, key);
        }
        
        public int ModifyDrugsBaseApply(Maptool.DrugsBaseService.DrugsBaseApply model, string key) {
            return base.Channel.ModifyDrugsBaseApply(model, key);
        }
        
        public int ModifyDrugsBaseApplyZyc(Maptool.DrugsBaseService.DrugsBaseApplyZyc model, string key) {
            return base.Channel.ModifyDrugsBaseApplyZyc(model, key);
        }
        
        public int DeleteDrugsBaseApply(string id, string key) {
            return base.Channel.DeleteDrugsBaseApply(id, key);
        }
        
        public int DeleteDrugsBaseApplyZyc(string id, string key) {
            return base.Channel.DeleteDrugsBaseApplyZyc(id, key);
        }
        
        public Maptool.DrugsBaseService.DrugsBaseApply[] GetDrugsBaseApplyList(out int recordCount, out int pageCount, int PageSize, int PageIndex, string source, string[] fields, string[] values, string key) {
            return base.Channel.GetDrugsBaseApplyList(out recordCount, out pageCount, PageSize, PageIndex, source, fields, values, key);
        }
        
        public Maptool.DrugsBaseService.DrugsBaseApplyZyc[] GetDrugsBaseApplyZycList(out int recordCount, out int pageCount, int PageSize, int PageIndex, string source, string[] fields, string[] values, string key) {
            return base.Channel.GetDrugsBaseApplyZycList(out recordCount, out pageCount, PageSize, PageIndex, source, fields, values, key);
        }
        
        public bool AddDrugsImageApplyList(Maptool.DrugsBaseService.DrugsImageApply[] list, string key) {
            return base.Channel.AddDrugsImageApplyList(list, key);
        }
        
        public bool SetDrugsImageApply(int goods_id, int type, string key) {
            return base.Channel.SetDrugsImageApply(goods_id, type, key);
        }
        
        public bool DeleteDrugsImageApply(string[] list, string key) {
            return base.Channel.DeleteDrugsImageApply(list, key);
        }
        
        public bool DeleteDrugsImageApplyId(int id, string key, int type) {
            return base.Channel.DeleteDrugsImageApplyId(id, key, type);
        }
        
        public System.Data.DataSet GetDrugsbaseAllList(int PageSize, int PageIndex, string[] where, string[] values, bool drugs, string authKey) {
            return base.Channel.GetDrugsbaseAllList(PageSize, PageIndex, where, values, drugs, authKey);
        }
        
        public System.Data.DataSet GetDrugsImageApplyList(int PageSize, int PageIndex, string source, string[] where, string[] values, string authKey) {
            return base.Channel.GetDrugsImageApplyList(PageSize, PageIndex, source, where, values, authKey);
        }
        
        public Maptool.DrugsBaseService.DrugsImageApply[] GetListArray(string strWhere, int type, string source, string key) {
            return base.Channel.GetListArray(strWhere, type, source, key);
        }
        
        public bool AddDrugsImageApply(Maptool.DrugsBaseService.DrugsImageApply model, string authKey) {
            return base.Channel.AddDrugsImageApply(model, authKey);
        }
        
        public bool UpdateDrugsImageApply(Maptool.DrugsBaseService.DrugsImageApply model, string authKey) {
            return base.Channel.UpdateDrugsImageApply(model, authKey);
        }
        
        public string[] GetDrugsBaseEnum(Maptool.DrugsBaseService.DrugsBaseEnum de) {
            return base.Channel.GetDrugsBaseEnum(de);
        }
        
        public System.Data.DataSet GetDrugsBase_Pharm(string key) {
            return base.Channel.GetDrugsBase_Pharm(key);
        }
        
        public System.Data.DataSet GetDrugsBase_Pharm2(string ids, string key) {
            return base.Channel.GetDrugsBase_Pharm2(ids, key);
        }
        
        public System.Data.DataSet GetOtcClass(string key) {
            return base.Channel.GetOtcClass(key);
        }
        
        public System.Data.DataSet GetOtcClass2(string ids, string key) {
            return base.Channel.GetOtcClass2(ids, key);
        }
        
        public int AddDrugsBase_Enterprise(string Name, decimal lng, decimal lat, int Province, int City, int Borough, string key) {
            return base.Channel.AddDrugsBase_Enterprise(Name, lng, lat, Province, City, Borough, key);
        }
        
        public Maptool.DrugsBaseService.EnterpriseLocation[] SelectCompanyName(string q) {
            return base.Channel.SelectCompanyName(q);
        }
        
        public Maptool.DrugsBaseService.EnterpriseLocation[] GetEnterpriseList() {
            return base.Channel.GetEnterpriseList();
        }
    }
}
