//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpToDataCentreService.SynFromServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SynFromServiceReference.synFromService1Soap")]
    public interface synFromService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddLog(string msg, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetStatus(ErpToDataCentreService.SynFromServiceReference.TableSyn ts, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataColumn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDataColumn(ErpToDataCentreService.SynFromServiceReference.TableSyn ts, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Config_CompanyType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Config_CompanyType(ErpToDataCentreService.SynFromServiceReference.TableSyn ts, string key);
        
        // CODEGEN: 参数“data”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ErpToDataCentreService.SynFromServiceReference.AddResponse Add(ErpToDataCentreService.SynFromServiceReference.AddRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TableSyn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string enterpriseIDField;
        
        private string tableNameField;
        
        private string[] columbNameField;
        
        private int intervalField;
        
        private string pkField;
        
        private string sqlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EnterpriseID {
            get {
                return this.enterpriseIDField;
            }
            set {
                this.enterpriseIDField = value;
                this.RaisePropertyChanged("EnterpriseID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] ColumbName {
            get {
                return this.columbNameField;
            }
            set {
                this.columbNameField = value;
                this.RaisePropertyChanged("ColumbName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int interval {
            get {
                return this.intervalField;
            }
            set {
                this.intervalField = value;
                this.RaisePropertyChanged("interval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string pk {
            get {
                return this.pkField;
            }
            set {
                this.pkField = value;
                this.RaisePropertyChanged("pk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sql {
            get {
                return this.sqlField;
            }
            set {
                this.sqlField = value;
                this.RaisePropertyChanged("sql");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ErpToDataCentreService.SynFromServiceReference.TableSyn ts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string key;
        
        public AddRequest() {
        }
        
        public AddRequest(ErpToDataCentreService.SynFromServiceReference.TableSyn ts, byte[] data, string key) {
            this.ts = ts;
            this.data = data;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int AddResult;
        
        public AddResponse() {
        }
        
        public AddResponse(int AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface synFromService1SoapChannel : ErpToDataCentreService.SynFromServiceReference.synFromService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class synFromService1SoapClient : System.ServiceModel.ClientBase<ErpToDataCentreService.SynFromServiceReference.synFromService1Soap>, ErpToDataCentreService.SynFromServiceReference.synFromService1Soap {
        
        public synFromService1SoapClient() {
        }
        
        public synFromService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public synFromService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public synFromService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public synFromService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddLog(string msg, int type) {
            base.Channel.AddLog(msg, type);
        }
        
        public int GetStatus(ErpToDataCentreService.SynFromServiceReference.TableSyn ts, string key) {
            return base.Channel.GetStatus(ts, key);
        }
        
        public string GetDataColumn(ErpToDataCentreService.SynFromServiceReference.TableSyn ts, string key) {
            return base.Channel.GetDataColumn(ts, key);
        }
        
        public System.Data.DataSet Config_CompanyType(ErpToDataCentreService.SynFromServiceReference.TableSyn ts, string key) {
            return base.Channel.Config_CompanyType(ts, key);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ErpToDataCentreService.SynFromServiceReference.AddResponse ErpToDataCentreService.SynFromServiceReference.synFromService1Soap.Add(ErpToDataCentreService.SynFromServiceReference.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public int Add(ErpToDataCentreService.SynFromServiceReference.TableSyn ts, byte[] data, string key) {
            ErpToDataCentreService.SynFromServiceReference.AddRequest inValue = new ErpToDataCentreService.SynFromServiceReference.AddRequest();
            inValue.ts = ts;
            inValue.data = data;
            inValue.key = key;
            ErpToDataCentreService.SynFromServiceReference.AddResponse retVal = ((ErpToDataCentreService.SynFromServiceReference.synFromService1Soap)(this)).Add(inValue);
            return retVal.AddResult;
        }
    }
}
