//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpShopService.BLL.com {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.APISoap")]
    public interface APISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMember", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendMember(System.Data.DataSet ds, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddExpirationTimeProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddExpirationTimeProduct(System.Data.DataSet ds, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ModifyCustomer(System.Data.DataSet ds, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteCustomer(System.Data.DataSet ds, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddProduct(System.Data.DataSet ds, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EditProduct(System.Data.DataSet ds, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteProduct(string spid, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ErpShopService.BLL.com.OrderList[] GetOrderList(string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNotFiling", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetNotFiling(string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrdersMQ_1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateOrdersMQ_1(string orderid, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SynStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SynStock(System.Data.DataSet ds, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SynPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SynPrice(System.Data.DataSet ds, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrderStatusForErp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateOrderStatusForErp(string orderid, string spid, int OrderStatus, string authKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SyncMemberBusinessScope", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SyncMemberBusinessScope(System.Data.DataSet ds, string authKey);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Orders orderField;
        
        private string salesmanField;
        
        private OrderProduct[] liField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Orders order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("order");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string salesman {
            get {
                return this.salesmanField;
            }
            set {
                this.salesmanField = value;
                this.RaisePropertyChanged("salesman");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public OrderProduct[] li {
            get {
                return this.liField;
            }
            set {
                this.liField = value;
                this.RaisePropertyChanged("li");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Orders : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string dwidField;
        
        private string orderIdField;
        
        private string userNameField;
        
        private int receiverIdField;
        
        private System.DateTime shopDateField;
        
        private System.DateTime orderDateField;
        
        private string consigneeRealNameField;
        
        private string consigneeNameField;
        
        private string consigneePhoneField;
        
        private string consigneeProvinceField;
        
        private string consigneeAddressField;
        
        private string consigneeZipField;
        
        private string consigneeTelField;
        
        private string consigneeFaxField;
        
        private string consigneeEmailField;
        
        private int paymentTypeField;
        
        private int paymentField;
        
        private decimal totalPriceField;
        
        private decimal feesField;
        
        private decimal otherFeesField;
        
        private int invoiceField;
        
        private string remarkField;
        
        private int orderStatusField;
        
        private int paymentStatusField;
        
        private int ogisticsStatusField;
        
        private System.Nullable<int> businessmanIDField;
        
        private string businessmanNameField;
        
        private int carriageField;
        
        private int orderTypeField;
        
        private string contractNoField;
        
        private string consigneeCityField;
        
        private string consigneeBoroughField;
        
        private string consigneeConstructionSignsField;
        
        private string consignesTimeField;
        
        private decimal tradeFeesField;
        
        private int tradeFeesPayField;
        
        private int editerField;
        
        private int parentidField;
        
        private string parentCorpNameField;
        
        private int billingCorpField;
        
        private string billingCorpNameField;
        
        private int isBusinessCheckField;
        
        private System.Nullable<int> isFinancialReviewField;
        
        private System.Nullable<System.DateTime> businessCheckDateField;
        
        private System.Nullable<System.DateTime> financialCheckDateField;
        
        private bool isSendField;
        
        private int splitStatusField;
        
        private int sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dwid {
            get {
                return this.dwidField;
            }
            set {
                this.dwidField = value;
                this.RaisePropertyChanged("dwid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ReceiverId {
            get {
                return this.receiverIdField;
            }
            set {
                this.receiverIdField = value;
                this.RaisePropertyChanged("ReceiverId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime ShopDate {
            get {
                return this.shopDateField;
            }
            set {
                this.shopDateField = value;
                this.RaisePropertyChanged("ShopDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
                this.RaisePropertyChanged("OrderDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ConsigneeRealName {
            get {
                return this.consigneeRealNameField;
            }
            set {
                this.consigneeRealNameField = value;
                this.RaisePropertyChanged("ConsigneeRealName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ConsigneeName {
            get {
                return this.consigneeNameField;
            }
            set {
                this.consigneeNameField = value;
                this.RaisePropertyChanged("ConsigneeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ConsigneePhone {
            get {
                return this.consigneePhoneField;
            }
            set {
                this.consigneePhoneField = value;
                this.RaisePropertyChanged("ConsigneePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ConsigneeProvince {
            get {
                return this.consigneeProvinceField;
            }
            set {
                this.consigneeProvinceField = value;
                this.RaisePropertyChanged("ConsigneeProvince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ConsigneeAddress {
            get {
                return this.consigneeAddressField;
            }
            set {
                this.consigneeAddressField = value;
                this.RaisePropertyChanged("ConsigneeAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ConsigneeZip {
            get {
                return this.consigneeZipField;
            }
            set {
                this.consigneeZipField = value;
                this.RaisePropertyChanged("ConsigneeZip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ConsigneeTel {
            get {
                return this.consigneeTelField;
            }
            set {
                this.consigneeTelField = value;
                this.RaisePropertyChanged("ConsigneeTel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ConsigneeFax {
            get {
                return this.consigneeFaxField;
            }
            set {
                this.consigneeFaxField = value;
                this.RaisePropertyChanged("ConsigneeFax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ConsigneeEmail {
            get {
                return this.consigneeEmailField;
            }
            set {
                this.consigneeEmailField = value;
                this.RaisePropertyChanged("ConsigneeEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int PaymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
                this.RaisePropertyChanged("PaymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
                this.RaisePropertyChanged("Payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public decimal TotalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
                this.RaisePropertyChanged("TotalPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal Fees {
            get {
                return this.feesField;
            }
            set {
                this.feesField = value;
                this.RaisePropertyChanged("Fees");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal OtherFees {
            get {
                return this.otherFeesField;
            }
            set {
                this.otherFeesField = value;
                this.RaisePropertyChanged("OtherFees");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("OrderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int PaymentStatus {
            get {
                return this.paymentStatusField;
            }
            set {
                this.paymentStatusField = value;
                this.RaisePropertyChanged("PaymentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int OgisticsStatus {
            get {
                return this.ogisticsStatusField;
            }
            set {
                this.ogisticsStatusField = value;
                this.RaisePropertyChanged("OgisticsStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public System.Nullable<int> BusinessmanID {
            get {
                return this.businessmanIDField;
            }
            set {
                this.businessmanIDField = value;
                this.RaisePropertyChanged("BusinessmanID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string BusinessmanName {
            get {
                return this.businessmanNameField;
            }
            set {
                this.businessmanNameField = value;
                this.RaisePropertyChanged("BusinessmanName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int Carriage {
            get {
                return this.carriageField;
            }
            set {
                this.carriageField = value;
                this.RaisePropertyChanged("Carriage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public int OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("OrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string ContractNo {
            get {
                return this.contractNoField;
            }
            set {
                this.contractNoField = value;
                this.RaisePropertyChanged("ContractNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string ConsigneeCity {
            get {
                return this.consigneeCityField;
            }
            set {
                this.consigneeCityField = value;
                this.RaisePropertyChanged("ConsigneeCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string ConsigneeBorough {
            get {
                return this.consigneeBoroughField;
            }
            set {
                this.consigneeBoroughField = value;
                this.RaisePropertyChanged("ConsigneeBorough");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string ConsigneeConstructionSigns {
            get {
                return this.consigneeConstructionSignsField;
            }
            set {
                this.consigneeConstructionSignsField = value;
                this.RaisePropertyChanged("ConsigneeConstructionSigns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string ConsignesTime {
            get {
                return this.consignesTimeField;
            }
            set {
                this.consignesTimeField = value;
                this.RaisePropertyChanged("ConsignesTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public decimal TradeFees {
            get {
                return this.tradeFeesField;
            }
            set {
                this.tradeFeesField = value;
                this.RaisePropertyChanged("TradeFees");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public int TradeFeesPay {
            get {
                return this.tradeFeesPayField;
            }
            set {
                this.tradeFeesPayField = value;
                this.RaisePropertyChanged("TradeFeesPay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public int Editer {
            get {
                return this.editerField;
            }
            set {
                this.editerField = value;
                this.RaisePropertyChanged("Editer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public int parentid {
            get {
                return this.parentidField;
            }
            set {
                this.parentidField = value;
                this.RaisePropertyChanged("parentid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string parentCorpName {
            get {
                return this.parentCorpNameField;
            }
            set {
                this.parentCorpNameField = value;
                this.RaisePropertyChanged("parentCorpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public int BillingCorp {
            get {
                return this.billingCorpField;
            }
            set {
                this.billingCorpField = value;
                this.RaisePropertyChanged("BillingCorp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string BillingCorpName {
            get {
                return this.billingCorpNameField;
            }
            set {
                this.billingCorpNameField = value;
                this.RaisePropertyChanged("BillingCorpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public int IsBusinessCheck {
            get {
                return this.isBusinessCheckField;
            }
            set {
                this.isBusinessCheckField = value;
                this.RaisePropertyChanged("IsBusinessCheck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public System.Nullable<int> isFinancialReview {
            get {
                return this.isFinancialReviewField;
            }
            set {
                this.isFinancialReviewField = value;
                this.RaisePropertyChanged("isFinancialReview");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public System.Nullable<System.DateTime> BusinessCheckDate {
            get {
                return this.businessCheckDateField;
            }
            set {
                this.businessCheckDateField = value;
                this.RaisePropertyChanged("BusinessCheckDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=45)]
        public System.Nullable<System.DateTime> FinancialCheckDate {
            get {
                return this.financialCheckDateField;
            }
            set {
                this.financialCheckDateField = value;
                this.RaisePropertyChanged("FinancialCheckDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public bool IsSend {
            get {
                return this.isSendField;
            }
            set {
                this.isSendField = value;
                this.RaisePropertyChanged("IsSend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public int splitStatus {
            get {
                return this.splitStatusField;
            }
            set {
                this.splitStatusField = value;
                this.RaisePropertyChanged("splitStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public int source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderProduct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string orderIdField;
        
        private System.Nullable<int> proIdField;
        
        private string proNameField;
        
        private System.Nullable<decimal> proPriceField;
        
        private System.Nullable<int> proNumField;
        
        private System.Nullable<System.DateTime> addTimeField;
        
        private string pro_pnoField;
        
        private string pro_pdateField;
        
        private string storageIDField;
        
        private string extend1Field;
        
        private int isExpirationProductField;
        
        private int idenField;
        
        private string jigidField;
        
        private System.Nullable<int> statusField;
        
        private bool issplitField;
        
        private string spidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> ProId {
            get {
                return this.proIdField;
            }
            set {
                this.proIdField = value;
                this.RaisePropertyChanged("ProId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ProName {
            get {
                return this.proNameField;
            }
            set {
                this.proNameField = value;
                this.RaisePropertyChanged("ProName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> ProPrice {
            get {
                return this.proPriceField;
            }
            set {
                this.proPriceField = value;
                this.RaisePropertyChanged("ProPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> ProNum {
            get {
                return this.proNumField;
            }
            set {
                this.proNumField = value;
                this.RaisePropertyChanged("ProNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> AddTime {
            get {
                return this.addTimeField;
            }
            set {
                this.addTimeField = value;
                this.RaisePropertyChanged("AddTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string pro_pno {
            get {
                return this.pro_pnoField;
            }
            set {
                this.pro_pnoField = value;
                this.RaisePropertyChanged("pro_pno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string pro_pdate {
            get {
                return this.pro_pdateField;
            }
            set {
                this.pro_pdateField = value;
                this.RaisePropertyChanged("pro_pdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StorageID {
            get {
                return this.storageIDField;
            }
            set {
                this.storageIDField = value;
                this.RaisePropertyChanged("StorageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Extend1 {
            get {
                return this.extend1Field;
            }
            set {
                this.extend1Field = value;
                this.RaisePropertyChanged("Extend1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int IsExpirationProduct {
            get {
                return this.isExpirationProductField;
            }
            set {
                this.isExpirationProductField = value;
                this.RaisePropertyChanged("IsExpirationProduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int iden {
            get {
                return this.idenField;
            }
            set {
                this.idenField = value;
                this.RaisePropertyChanged("iden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string jigid {
            get {
                return this.jigidField;
            }
            set {
                this.jigidField = value;
                this.RaisePropertyChanged("jigid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool issplit {
            get {
                return this.issplitField;
            }
            set {
                this.issplitField = value;
                this.RaisePropertyChanged("issplit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string spid {
            get {
                return this.spidField;
            }
            set {
                this.spidField = value;
                this.RaisePropertyChanged("spid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APISoapChannel : ErpShopService.BLL.com.APISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APISoapClient : System.ServiceModel.ClientBase<ErpShopService.BLL.com.APISoap>, ErpShopService.BLL.com.APISoap {
        
        public APISoapClient() {
        }
        
        public APISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendMember(System.Data.DataSet ds, string authKey) {
            return base.Channel.SendMember(ds, authKey);
        }
        
        public bool AddExpirationTimeProduct(System.Data.DataSet ds, string authKey) {
            return base.Channel.AddExpirationTimeProduct(ds, authKey);
        }
        
        public bool ModifyCustomer(System.Data.DataSet ds, string authKey) {
            return base.Channel.ModifyCustomer(ds, authKey);
        }
        
        public bool DeleteCustomer(System.Data.DataSet ds, string authKey) {
            return base.Channel.DeleteCustomer(ds, authKey);
        }
        
        public bool AddProduct(System.Data.DataSet ds, string authKey) {
            return base.Channel.AddProduct(ds, authKey);
        }
        
        public bool EditProduct(System.Data.DataSet ds, string authKey) {
            return base.Channel.EditProduct(ds, authKey);
        }
        
        public bool DeleteProduct(string spid, string authKey) {
            return base.Channel.DeleteProduct(spid, authKey);
        }
        
        public ErpShopService.BLL.com.OrderList[] GetOrderList(string authKey) {
            return base.Channel.GetOrderList(authKey);
        }
        
        public string GetNotFiling(string authKey) {
            return base.Channel.GetNotFiling(authKey);
        }
        
        public void UpdateOrdersMQ_1(string orderid, string authKey) {
            base.Channel.UpdateOrdersMQ_1(orderid, authKey);
        }
        
        public void SynStock(System.Data.DataSet ds, string authKey) {
            base.Channel.SynStock(ds, authKey);
        }
        
        public void SynPrice(System.Data.DataSet ds, string authKey) {
            base.Channel.SynPrice(ds, authKey);
        }
        
        public void UpdateOrderStatusForErp(string orderid, string spid, int OrderStatus, string authKey) {
            base.Channel.UpdateOrderStatusForErp(orderid, spid, OrderStatus, authKey);
        }
        
        public void SyncMemberBusinessScope(System.Data.DataSet ds, string authKey) {
            base.Channel.SyncMemberBusinessScope(ds, authKey);
        }
    }
}
